[package]
authors = ["Philpax"]
edition = "2021"
name = "wgpu-openxr-example"
version = "0.1.0"

[dependencies]
anyhow = "1.0.65"
ash = "0.37.0"
futures = "0.3.24"
openxr = {version = "0.17.0", features = ["linked", "static"]}
wgpu = "0.13.1"
wgpu-hal = "0.13.1"
winit = "0.27.3"
